### ISSUE TITLE
Small bug in  m_state_model

### ISSUE THREAD

**Issue by simo517L** [AdvancedR-2021/hmm#3]
When i tried the  m_state_model function form the vignette, with value 7, is get 

> m_state_model(7)
[1] 756.5481 903.5537
Warning messages:
1: In log_f[j, k] <- k + log(sum(exp(log_v_hat_jk - k))) :
  NAs introduced by coercion to integer range
2: In log_f[j, k] <- k + log(sum(exp(log_v_hat_jk - k))) :
  NAs introduced by coercion to integer range

I still get a value, but it may be wise to find out why this happens.

**Comment by ghost** [comment]
I think this was caused by value underflow in estimating Gamma - it should now be fixed
